### PR TITLE
convolution formula fixed

### PR DESCRIPTION
**Pull request by Moeinh77**

### CODE REVIEW

**Comment by yl-1993** [comment]
@Moeinh77 Thanks! Looks good to me.
Could you please format it with pep8 before merging?

**Comment by Moeinh77** [comment]
what's pep 8?

**Comment by yl-1993** [comment]
[pep8](https://www.python.org/dev/peps/pep-0008/) is a style guide for python, but it seems that this repo does not follow this style currently.
 I will merge this PR first and format the code uniformly.

**Comment by Moeinh77** [comment]
I changed a couple of other settings and managed to reach 92% with your
implementation. I'll try to push those changes too

*------------------*
*Moein Hasani*

*find me :*

*LinkedIn account <https://www.linkedin.com/in/moein-hasani/>*

*Github account <https://github.com/Moeinh77>*

**Comment by yl-1993** [comment]
Thanks! Feel free to open a new PR for that.

**Pull request merged**
